<?php
$this->breadcrumbs=array(
	'Tcontracts'=>array('index'),
	$model->contr_num,
);

$this->menu=array(
	array('label'=>'Tcontracts', 'itemOptions'=>array('class'=>'nav-header')),
	array('label'=>'List Intra Broker','icon'=>'list','url'=>array('indexintra')),
);
?>

<h1>View Contract Intra Broker #<?php echo $model->contr_num; ?></h1>

<?php AHelper::showFlash($this) ?> <!-- show flash -->

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		'contr_num',
		array('label'=>'Beli / Jual', 'value'=>AConstant::$contract_belijual[$model->belijual]),
		array('name'=>'contr_dt','type'=>'date'),
		array('name'=>'due_dt_for_amt','type'=>'date'),
		'stk_cd',
		'counter.stk_desc',
		'qty',
		'price',
		'client_cd',
		'client.client_name',
		'mrkt_type',
		!empty($model->sell_broker_cd)? 'sell_broker_cd':'buy_broker_cd',
		!empty($model->sell_broker_cd)? array('name'=>'sellbroker.client_name','type'=>'raw','label'=>'Sell Broker Name'):
												   array('name'=>'buybroker.client_name','type'=>'raw','label'=>'Buy Broker Name'),
		array('name'=>'brok_perc', 'value'=>$model->brok_perc/100),
		array('name'=>'gain_loss_amt', 'value'=>$model->gain_loss_amt/100),
	/*
		'adv_paymt_flg',
		'adv_scrip_flg',
		array('name'=>'amend_dt','type'=>'date'),
		array('name'=>'kpei_due_dt','type'=>'date'),
		array('name'=>'ksei_due_dt','type'=>'date'),
		'amt_for_curr',
		'brch_cd',
		'brok',
		'brok_perc',
		'can_amd_flg',
		'client_cd',
		'client_type',
		'commission',
		array('name'=>'contr_dt','type'=>'date'),
		'contr_num',
		'contr_stat',
		'contra_flag',
		'contra_num',
		array('name'=>'cre_dt','type'=>'date'),
		'curr_cd',
		array('name'=>'due_dt_for_amt','type'=>'date'),
		array('name'=>'due_dt_for_cert','type'=>'date'),
		'exch_cd',
		'gain_loss_amt',
		'gain_loss_ind',
		'levy_perc',
		array('name'=>'lot_size','type'=>'number'),
		'mrkt_type',
		'net',
		'odd_lot_ind',
		'par_val',
		array('name'=>'paymt_last_dt','type'=>'date'),
		'pph',
		'pph_perc',
		'price',
		array('name'=>'qty','type'=>'number'),
		'rem_cd',
		array('name'=>'scrip_days_c','type'=>'number'),
		array('name'=>'scrip_last_dt','type'=>'date'),
		array('name'=>'sess_no','type'=>'number'),
		'sett_for_curr',
		array('name'=>'sett_qty','type'=>'number'),
		'sett_val',
		'settle_curr_tmp',
		'status',
		'stk_cd',
		'trans_levy',
		array('name'=>'upd_dt','type'=>'date'),
		'user_id',
		'val',
		'val_stat',
		'vat',
		'pph_other_val',
		'main_rem_cd',
		'recov_charge_flg',
		'record_source',
		'rvpv_number',
		'doc_ref_num',
		'levy_tax',
		'buy_broker_cd',
		'sell_broker_cd',
		array('name'=>'approved_dt','type'=>'date'),
		'approved_by',
		'approved_stat',
	 * 
	 */
	),
)); ?>
